name: create-testenv-aws-infra

on:
  workflow_dispatch:
  push:

jobs:
  create-comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Echo commit-hash
        run: echo ${{ $GITHUB_SHA}}





