name: create-testenv-aws-infra

on:
  workflow_dispatch:
  push:

jobs:
  create-comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Check Hash
        run: echo "${{ env.hash }}"





